version: '3'

services:
  build: .
  flask_app:
  ports:
    - "5000:5000"
  environment:
   - FLASK_ENV=development
   - DATABASE_HOST=db
   - DATABASE_USER=root
   - DATABASE_PASSWORD=fatec
   - DATABASE_BD=newsletter
  depends_on:
    - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=newsletter
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
