FROM python:3.9

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENV MYSQL_HOST=172.17.0.2
ENV MYSQL_USER=davi
ENV MYSQL_PASSWORD=davi
ENV MYSQL_DATABASE=newsletter

CMD ["python", "app.py"]
